---
title: "R Codes for Project - Group 11"
author: "Clementine Wu 332824497 | Rachel Ma 390144473 | Xingyu Chen 320797399 | Rong Zhu 357803772"
format: html
editor: visual
---

**General Set-up**

```{r}
packages_needed <-  c( 
  "GGally",
  'tidymodels',
  'lubridate',
  "themis", 
  "kknn", 
  "rpart",  
  "rpart.plot", 
  "baguette", 
  "ranger", 
  "xgboost", 
  "lightgbm", "bonsai" 
  , "parallel", "future" 
)
packages_to_install <- packages_needed[!packages_needed %in%
                                         installed.packages()]
sapply(packages_to_install, install.packages,
       dependencies=TRUE, repos="https://cloud.r-project.org")
sapply(packages_needed, require, character=TRUE)

library(tidymodels)
library(knitr)
library(tidyverse)
library(readxl)
library(xtable)
library(GGally)
library(lubridate)

#parallel processing
cores <- parallel::detectCores(logical = TRUE)
plan(multisession) 

# import data set
bank_data <- read_csv("data7/bank_A_transactions_20240731.csv")

# add the hour column
bank_with_hour <- bank_data |>
  mutate(NewDate = ymd_hms(TransactionDate), TransactionHour = hour(NewDate))

# categorize the amount bin
bank_with_hour$AmountBin <- cut(bank_with_hour$TransactionAmount, 
                    breaks = c(-1, 100, 500, 1000, 5000, Inf), 
                    labels = c("0-100", "100-500", "500-1000", "1000-5000", "5000+"))

# split agent attribute to Equipment_Sort
bank_data <- bank_with_hour |>
  mutate(agent_binary = ifelse(agent == "ATM", 0, 1),
         agent_binary = ifelse(is.na(agent), 1, agent_binary),
         AmountCategory = AmountBin)



# Convert agent_binary to a factor with levels 0 and 1
bank_data <- bank_data |>
  mutate(agent_binary = factor(agent_binary, levels = c(0, 1)))

# change the strings to factor (FraudLabel, Equipment_Sort)
bank_data$FraudLabel <- factor(bank_data$FraudLabel,
                                           levels = c("1", "0"),
                                           labels = c("Fraud", "Not Fraud"))


bank_data$joint_flag <- factor(bank_data$joint_flag,
                               levels = c("0", "1"),
                               labels = c("NotJoint", "Joint"))

# Convert character variables to factors
bank_data$TransactionType <- as.factor(bank_data$TransactionType)
bank_data$AmountCategory <- as.factor(bank_data$AmountCategory)

# Verify the data type
str(bank_data$agent_binary)

# check data structure
str(bank_data)

# summary of dataset
summary(bank_data)

# Count the number of NA values per column
colSums(is.na(bank_data))
```

**Select Variables as Predictors**

```{r}
# create a new dataset where variables necessary

# bank_selected <- bank_data %>% slice_sample(n=500000)|>
#  select(TransactionID, TransactionType, FraudLabel, Age, joint_flag, TransactionHour, AmountCategory)

bank_selected <- bank_data |>
  select(TransactionID, TransactionType, FraudLabel, Age, joint_flag, TransactionHour, AmountCategory)

# inspect the dataset
head(bank_selected)    
str(bank_selected)
```

**Data Partition and Folds Creation**

```{r}
#data-partition

set.seed(222)

# Split 3/4 of the data into the training set 
fraud_split <- initial_split(bank_selected, prop = 0.75, strata = FraudLabel)

# Create data frames for the three sets:
fraud_train_data <- training(fraud_split)
fraud_test_data  <- testing(fraud_split)


# Create folds
set.seed(666)
cv_folds <- vfold_cv(fraud_train_data, 
                     v = 10, 
                     strata = FraudLabel) 
```

**Recipe Creation**

```{r}
# Create recipe
fraud_recipe <- 
  # create recipe and specify formula
  recipe(FraudLabel ~ TransactionType+Age+TransactionHour+TransactionID+AmountCategory, data = fraud_train_data)  |>
  # update role of ID variables  
  update_role(TransactionID, new_role = "ID") |>  
  step_rm(TransactionID)  |># Exclude TransactionID from the recipe
  step_naomit(everything(), skip = TRUE) |> 
  # normalize variables  
  step_normalize(all_numeric_predictors())  |> 
  # create dummy variables for nominal predictors
  step_dummy(all_nominal(), -all_outcomes()) %>%  # Convert factors to dummy variables
  step_smote(FraudLabel, over_ratio = 1)  # Apply SMOTE to the outcome variable
glimpse(fraud_recipe)

# Prep the recipe
# Bake the prepared recipe
glimpse(fraud_train_data)
fraud_recipe |> 
  prep() |> 
  bake(fraud_train_data) 
```

**Develop Models**

```{r}
#lr-model-defn
lr_model <- 
  logistic_reg() |> 
  set_engine("glm")

lr_wflow <- workflow() |> 
  add_model(lr_model) |> 
  add_recipe(fraud_recipe)
lr_wflow


#xgb-model-defn

xgb_model <- 
  boost_tree() |>
  set_engine("xgboost" ) |>
  set_mode("classification") 

xgb_wflow <- 
  workflow() |> 
  add_model(xgb_model) |> 
  add_recipe(fraud_recipe)

#lgbm-model-defn

lgbm_model <- 
  boost_tree() |>
  set_engine("lightgbm" ) |>
  set_mode("classification") 

lgbm_wflow <- 
  workflow() |> 
  add_model(lgbm_model) |> 
  add_recipe(fraud_recipe)
```

**Metrics and Resamples**

```{r}
# metrics
fraud_metrics <- metric_set(accuracy, roc_auc, sensitivity, specificity, bal_accuracy,
                            ppv, npv)
                            ## other metrics are possible, e.g. 
                            #, f_meas, kap, recall, precision


# set the resamples
lr_res <- lr_wflow |>
  fit_resamples(
    resamples = cv_folds, 
    metrics = fraud_metrics,
    control = control_grid(save_pred = TRUE,
                           parallel_over = "everything")
  ) 


#xgb

xgb_res <- xgb_wflow |>
  fit_resamples(
    resamples = cv_folds, 
    metrics = fraud_metrics,
    control = control_grid(save_pred = TRUE,
                           parallel_over = "everything")
  ) 



#lgbm
lgbm_res <- lgbm_wflow |>
  fit_resamples(
    resamples = cv_folds, 
    metrics = fraud_metrics,
    control = control_grid(save_pred = TRUE,
                           parallel_over = "everything")
  ) 
```

**Compare the models**

```{r}
# get-res

all_res <- 
  bind_rows(
    lr_res   |> collect_metrics(summarize = TRUE) |> mutate(model = "Logistic Regression"),
    xgb_res  |> collect_metrics(summarize = TRUE) |> mutate(model = "XGBoost"),
    lgbm_res |> collect_metrics(summarize = TRUE) |> mutate(model = "LightGBM")
  )

# Combine predictions
all_pred <- 
  bind_rows(
    lr_res   |> collect_predictions()  |> mutate(model = "Logistic Regression"),
    xgb_res  |> collect_predictions()  |> mutate(model = "XGBoost"),
    lgbm_res |> collect_predictions()  |> mutate(model = "LightGBM")
  )

#plot-roc-by-fold
all_pred
# inspect results
# notice the variability between each run
all_pred |> 
  group_by(id,model) |># id contains our folds
  roc_curve(FraudLabel, ".pred_Fraud") |>
  autoplot(aes(col = model)) + facet_wrap(facets = vars(model)) +
  theme(legend.position = "none") + 
  labs(title = "ROC by fold for selected algorithms")

#plot-res

all_res |> 
  ggplot() + 
  geom_col(aes(y = reorder(model, desc(model)), x = mean, fill = model)) +
  facet_wrap(facets = vars(.metric), ncol = 3) +
  labs(y = "model") + 
  xlim(0,1)+
  theme(panel.border = element_rect(colour = "black", fill=NA, linewidth=1))+
  theme(legend.position = "none") 

#Best performing model by metric

# best-by-metric
 
all_res |> 
  group_by(.metric) |> 
  slice_max(mean) |>  
  select(.metric, mean, model)
```

```{r}
#Select the best model using weighted mertric

sensitivity_specificity_res <- all_res %>%
  filter(.metric %in% c("sensitivity", "specificity")) %>%
  select(model, .metric, mean)

sensitivity_specificity_wide <- sensitivity_specificity_res %>%
  pivot_wider(names_from = .metric, values_from = mean)

sensitivity_specificity_wide <- sensitivity_specificity_wide %>%
  mutate(weighted_value = 0.6 * sensitivity + 0.4 * specificity)

sensitivity_specificity_wide
```

```{r}
#Finalise the workflow
final_wflow <- xgb_wflow 

# Evaluate this last fitted model on the test data
# Do a final fit (train on training data and test on testing data)
fitted_model <- final_wflow |>
  fit(data = fraud_train_data)

final_fit <- 
  final_wflow |>
  last_fit(fraud_split,
           metrics = fraud_metrics)

final_res <- final_fit |>  collect_metrics()
final_res

final_pred <- final_fit |>
  collect_predictions() 


final_pred |> 
  roc_curve(truth = FraudLabel, .pred_Fraud) |> 
  autoplot()

#Confusion matrix 

final_conf <- final_pred |>
  conf_mat(truth = FraudLabel, .pred_class) 
final_conf

summary(final_conf) |> print(n = 13)

```

**Confusion Matrix Heatmap for test data**

```{r}
autoplot(final_conf, type = "heatmap") +
  scale_fill_gradientn(colors = c("lightcyan", "lightblue", "#9ACEEB", "#9AEBE4")) +
  labs(title = "Classification Results Summary",
       x = "Predicted Label",
       y = "Actual Label") +
  theme_minimal()

```

**Feature Importance**

```{r}
booster_model <- extract_fit_engine(final_fit)

class(booster_model)

model_feature_names <- booster_model$feature_names

importance <- xgb.importance(feature_names = model_feature_names, model = booster_model)

print(importance)
```
